# vim:ft=kitty

## name:     Gruvbox Material Dark Hard
## author:   Sainnhe
## license:  MIT
## upstream: https://github.com/catppuccin/kitty/blob/main/mocha.conf
## blurb:    Soothing pastel theme for the high-spirited!



# The basic colors
foreground              #f5e2c5
background              #040e0d
selection_foreground    #040e0d
selection_background    #3dd1b0

# Cursor colors
cursor                  #3dd1b0
cursor_text_color       #040e0d

# URL underline color when hovering with mouse
url_color               #7ad9a8

# Kitty window border colors
active_border_color     #7daea3
inactive_border_color   #3dd1b0
bell_border_color       #f5cd5b

# OS Window titlebar colors
wayland_titlebar_color system
macos_titlebar_color system

# Tab bar colors
active_tab_foreground   #040e0d
active_tab_background   #ff6048
inactive_tab_foreground #f5e2c5
inactive_tab_background #0a1816
tab_bar_background      #040e0d

# Colors for marks (marked text in the terminal)
mark1_foreground #040e0d
mark1_background #3dd1b0
mark2_foreground #040e0d
mark2_background #d3869b
mark3_foreground #040e0d
mark3_background #ff6048

# The 16 terminal colors

# black
color0 #040e0d
color8 #040e0d

# red
color1 #ff6048
color9 #ff6048

# green
color2  #3dd1b0
color10 #3dd1b0

# yellow
color3  #f5cd5b
color11 #f5cd5b

# blue
color4  #3dd1b0
color12 #3dd1b0

# magenta
color5  #ff6048
color13 #ff6048

# cyan
color6  #3dd1b0
color14 #3dd1b0

# white
color7  #f5e2c5
color15 #f5e2c5
