$mainbgcolor = rgb(0a1816)
$secondarybgcolor = rgb(1d3631)

$textmaincolor = rgb(f5e2c5)

$debug = rgb(FFFF00)

$accentcolor = rgb(3dd1b0)

$red = rgb(ff6048)
$orange = rgb(ffa478)
$yellow = rgb(f5cd5b)
$green = rgb(7ad9a8)
$aqua = rgb(3dd1b0)
$blue = rgb(5fc8d4)
$purple = rgb(5fc8d4)
