
$rosewater = rgb(7daea3)
$rosewaterAlpha = 7daea3

$flamingo = rgb(d3869b)
$flamingoAlpha = d3869b

$pink = rgb(d3869b)
$pinkAlpha = d3869b

$mauve = rgb(d3869b)
$mauveAlpha = d3869b

$red = rgb(7daea3)
$redAlpha = 7daea3

$maroon = rgb(eba0ac)
$maroonAlpha = eba0ac

$peach = rgb(e78a4e)
$peachAlpha = e78a4e

$yellow = rgb(d8a657)
$yellowAlpha = d8a657

$green = rgb(a9b665)
$greenAlpha = a9b665

$teal = rgb(7daea3)
$tealAlpha = 7daea3

$sky = rgb(7daea3)
$skyAlpha = 7daea3

$sapphire = rgb(0d138)
$sapphireAlpha = 0d138

$blue = rgb(0d138)
$blueAlpha = 0d138

$lavender = rgb(7daea3)
$lavenderAlpha = 7daea3

$text = rgb(7daea3)
$textAlpha = 7daea3

$subtext1 = rgb(7daea3)
$subtext1Alpha = 7daea3

$subtext0 = rgb(7daea3)
$subtext0Alpha = 7daea3

$overlay2 = rgb(7daea3)
$overlay2Alpha = 7daea3

$overlay1 = rgb(7daea3)
$overlay1Alpha = 7daea3

$overlay0 = rgb(6c7086)
$overlay0Alpha = 6c7086

$surface2 = rgb(585b70)
$surface2Alpha = 585b70

$surface1 = rgb(45475a)
$surface1Alpha = 45475a

$surface0 = rgb(313244)
$surface0Alpha = 313244

$base = rgb(1e1e2e)
$baseAlpha = 1e1e2e

$mantle = rgb(181825)
$mantleAlpha = 181825

$crust = rgb(11111b)
$crustAlpha = 11111b
