$mainbgcolor = rgb(1e1e2e)
$secondarybgcolor = rgb(313244)

$textmaincolor = rgb(cdd6f4)

$debug = rgb(FFFF00)

$accentcolor = rgb(89b4fa)

$red = rgb(f38ba8)
$orange = rgb(fab387)
$yellow = rgb(f9e2af)
$green = rgb(a6e3a1)
$aqua = rgb(94e2d5)
$blue = rgb(89b4fa)
$purple = rgb(cba6f7)
