$mainbgcolor = rgb(1d2021)
$secondarybgcolor = rgb(282828)

$textmaincolor = rgb(f5e2c5)

$debug = rgb(FFFF00)

$accentcolor = rgb(7daea3)

$red = rgb(ea6962)
$orange = rgb(e78a4e)
$yellow = rgb(d8a657)
$green = rgb(a9b665)
$aqua = rgb(89b482)
$blue = rgb(7daea3)
$purple = rgb(d3869b)
