
$rosewater = rgb(3dd1b0)
$rosewaterAlpha = 3dd1b0

$flamingo = rgb(e89aa8)
$flamingoAlpha = e89aa8

$pink = rgb(e89aa8)
$pinkAlpha = e89aa8

$mauve = rgb(e89aa8)
$mauveAlpha = e89aa8

$red = rgb(3dd1b0)
$redAlpha = 3dd1b0

$maroon = rgb(e89aa8)
$maroonAlpha = e89aa8

$peach = rgb(ffa478)
$peachAlpha = ffa478

$yellow = rgb(f5cd5b)
$yellowAlpha = f5cd5b

$green = rgb(7ad9a8)
$greenAlpha = 7ad9a8

$teal = rgb(3dd1b0)
$tealAlpha = 3dd1b0

$sky = rgb(3dd1b0)
$skyAlpha = 3dd1b0

$sapphire = rgb(5fc8d4)
$sapphireAlpha = 5fc8d4

$blue = rgb(5fc8d4)
$blueAlpha = 5fc8d4

$lavender = rgb(3dd1b0)
$lavenderAlpha = 3dd1b0

$text = rgb(3dd1b0)
$textAlpha = 3dd1b0

$subtext1 = rgb(3dd1b0)
$subtext1Alpha = 3dd1b0

$subtext0 = rgb(3dd1b0)
$subtext0Alpha = 3dd1b0

$overlay2 = rgb(3dd1b0)
$overlay2Alpha = 3dd1b0

$overlay1 = rgb(3dd1b0)
$overlay1Alpha = 3dd1b0

$overlay0 = rgb(040e0d)
$overlay0Alpha = 040e0d

$surface2 = rgb(0a1816)
$surface2Alpha = 0a1816

$surface1 = rgb(0f211f)
$surface1Alpha = 0f211f

$surface0 = rgb(152a26)
$surface0Alpha = 152a26

$base = rgb(040e0d)
$baseAlpha = 040e0d

$mantle = rgb(181825)
$mantleAlpha = 181825

$crust = rgb(11111b)
$crustAlpha = 11111b
